In [1]:
import torch
from torch.nn.functional import pad

IGNORE = -100

torch pad的文档：https://pytorch.org/docs/stable/generated/torch.nn.functional.pad.html

In [7]:
a = torch.zeros(1, 2, 2)
a, a.shape

(tensor([[[0., 0.],
          [0., 0.]]]),
 torch.Size([1, 2, 2]))

In [9]:
pad2 = pad(a, (1, 1), value=IGNORE)
pad2, pad2.shape

(tensor([[[-100.,    0.,    0., -100.],
          [-100.,    0.,    0., -100.]]]),
 torch.Size([1, 2, 4]))

In [8]:
pad4 = pad(a, (1, 1, 0, 1), value=IGNORE)
pad4, pad4.shape

(tensor([[[-100.,    0.,    0., -100.],
          [-100.,    0.,    0., -100.],
          [-100., -100., -100., -100.]]]),
 torch.Size([1, 3, 4]))

In [11]:
pad6 = pad(a, (1, 1, 0, 1, 1, 0), value=IGNORE)
pad6, pad6.shape

(tensor([[[-100., -100., -100., -100.],
          [-100., -100., -100., -100.],
          [-100., -100., -100., -100.]],
 
         [[-100.,    0.,    0., -100.],
          [-100.,    0.,    0., -100.],
          [-100., -100., -100., -100.]]]),
 torch.Size([2, 3, 4]))